/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as GuaranteeRouteImport } from './routes/guarantee'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as IndexRouteImport } from './routes/index'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const GuaranteeRoute = GuaranteeRouteImport.update({
  id: '/guarantee',
  path: '/guarantee',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/guarantee': typeof GuaranteeRoute
  '/plan': typeof PlanRoute
  '/setup': typeof SetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/guarantee': typeof GuaranteeRoute
  '/plan': typeof PlanRoute
  '/setup': typeof SetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/guarantee': typeof GuaranteeRoute
  '/plan': typeof PlanRoute
  '/setup': typeof SetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checkin' | '/guarantee' | '/plan' | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkin' | '/guarantee' | '/plan' | '/setup'
  id: '__root__' | '/' | '/checkin' | '/guarantee' | '/plan' | '/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckinRoute: typeof CheckinRoute
  GuaranteeRoute: typeof GuaranteeRoute
  PlanRoute: typeof PlanRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarantee': {
      id: '/guarantee'
      path: '/guarantee'
      fullPath: '/guarantee'
      preLoaderRoute: typeof GuaranteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckinRoute: CheckinRoute,
  GuaranteeRoute: GuaranteeRoute,
  PlanRoute: PlanRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
